### ISSUE TITLE
LGPL is problematic for Rust programs

### ISSUE THREAD

**Issue by DemiMarie** [rpm-software-management/librpm.rs#21]
The LGPL is somewhat problematic for Rust programs: due to Rust’s transitive recompilation requirements, it essentially becomes equivalent to the GPL in many cases.

**Comment by tarcieri** [comment]
While for most other Rust projects I would have chosen MIT+Apache2, librpm.rs is a binding that links directly to, provides a thin facade over, and is useless without a LGPL library (i.e. librpm itself).

With that considered, there's little reason to choose anything else aside from making the licensing story more complex.

**Comment by DemiMarie** [comment]
To elaborate, the LGPL requires that if I use `librpm.rs` in a proprietary Rust program, users must be able to replace librpm AND `librpm.rs`.  The former is easy, but I am not aware of any way to do the latter without providing source code.

**Comment by tarcieri** [comment]
We can potentially consider changing the license if a combination of licenses is actually practically better than a single one, but we'd have to get buy-in from all contributors.

**Comment by dralley** [comment]
MPLv2 is the closest thing to LGPL that is convenient in Rust.  Source files of the original work are protected (if you modify them, the modifications need to be available under the MPLv2 license also) but derivative works are not restricted.

It's just an LGPL that draws the boundaries in terms of files rather than linking, more or less.

**Comment by aloncatz** [comment]
We'd like to use librpm.rs in a closed source project. However, to my understanding the LGPL license for librpm.rs prevents us from doing so because Rust compiles librpm.rs into our binary, effectively performing static linking. Since the librpm itself is LGPL, it does allow us to write our bindings because we will be linking to librpm dynamically. I wonder whether this was your intention when choosing the LGPL license, or perhaps you could reconsider.

**Comment by dralley** [comment]
Are you able to say anything about this project publicly?  If it's an internal-only tool or a SaaS, the license doesn't matter all that much (excepting of course AGPL and similar licenses), it would only apply in if you're distributing the resulting binary.

**Comment by dralley** [comment]
Then yes, complying with the LGPL would require one of two things:

* The ability to re-link the application with a modified version of librpm.rs, either dynamically (not really a thing in Rust) or statically (also probably not possible)
* The ability to recompile the application (which would require it to be open source)

The same is true of `rpm` (lib) except that dynamic linking is the norm for C libraries on linux so the compliance is free.

**Comment by dralley** [comment]
For what it's worth, https://github.com/Richterrettich/rpm-rs exists and is if anything a bit more complete right now than librpm.rs, it might be an option.  

(Though of course it would still be nice for the licensing situation to be fixed)

**Comment by ryao** [comment]
> MPLv2 is the closest thing to LGPL that is convenient in Rust. Source files of the original work are protected (if you modify them, the modifications need to be available under the MPLv2 license also) but derivative works are not restricted.

The CDDL 1.0 also has this property. It is slightly less burdensome than the MPLv2 since it does not require people distributing modified versions to describe how to obtain the original:

https://tldrlegal.com/license/common-development-and-distribution-license-(cddl-1.0)-explained
https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)

**Comment by dralley** [comment]
CDDL has problems with GPL compatibility though, and MPLv2 does not.

**Comment by ryao** [comment]
> CDDL has problems with GPL compatibility though, and MPLv2 does not.

In that case, you can dual-license the code CDDL/GPL to get around that like Netbeans and OSSv4 do. That should be equivalent to the MPLv2's secondary license scheme.

**Comment by Conan-Kudo** [comment]
If we were going to relicense this project, it would probably be to MPLv2, as that explicitly maintains GNU license compatibility. 

That said, we'd need agreement from the contributors to change it to the MPLv2:

* [ ] @tarcieri 
* [ ] @Conan-Kudo 
* [ ] @aplanas 
* [ ] @mkpankov

**Comment by Conan-Kudo** [comment]
Please state in a comment "I agree to have my contributions relicensed to the Mozilla Public License, version 2.0." and once they're all collected, I can change the license.

**Comment by Conan-Kudo** [comment]
Also ping @dralley

**Comment by tarcieri** [comment]
I agree

**Comment by dralley** [comment]
I agree to have my contributions relicensed to the Mozilla Public License, version 2.0.

**Comment by mkpankov** [comment]
I agree to have my contributions relicensed to the Mozilla Public License, version 2.0.

**Comment by tarcieri** [comment]
I think that's everyone?

**Comment by Conan-Kudo** [comment]
Sorry it took so long, but this is now done.
